config/routes.rb
Rails.application.routes.draw do
  
  resources :enrollments do
    get :my_students, on: :collection
  end
  devise_for :users
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
  namespace :charts do
    get 'money_makers'
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
  end
  root "home#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @courses= Course.all.limit(3)
    @latest_courses = Course.latest_courses
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews

    @top_rated_courses = Course.top_rated
    @popular_courses = Course.popular
    @purchased_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc).limit(3)
  end

  def activity
    if current_user.has_role?(:admin)
      @activities = PublicActivity::Activity.all
    else 
      redirect_to root_path, alert: "you aren't authorized brug"
    end
  end

  def analytics
    if current_user.has_role?(:admin)
      #@users = User.all
      #@enrollments = Enrollment.all
      #@courses = Course.all
    else 
      redirect_to root_path, alert: "you aren't authorized brug"
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activity.html.haml
- content_for :title do
  what   
  \|
  Activity
%h3
  .text-center 
    Activity
    .badge.bg-info 
      = @activities.count
%p
%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item 
      = activity.id
      = activity.trackable_type 
      = activity.trackable_id 
      = link_to activity.trackable, activity.trackable
      = activity.key 
      = activity.parameters 
      = activity.owner


  

app/views/home/analytics.html.haml
%h3
    Users Created
/= line_chart @users.group_by_day(:created_at).count
= line_chart charts_users_per_day_path

%h3 
    Enrollments 
/= column_chart @enrollments.group_by_day(:created_at).count
= column_chart charts_enrollments_per_day_path
%h3
    Course Popularity 

/= pie_chart @courses.group(:enrollments_count).count
/= pie_chart @enrollments.joins(:course).group(:'courses.title').count
= pie_chart charts_course_popularity_path

%h4.text-center
    Most Paid 
= bar_chart charts_money_makers_path

app/views/home/index.html.haml
- content_for :title do
  Whatever 
  \|
  Online Courses - Learn stuff

= line_chart User.group_by_day(:created_at).count
.mt-4.p-5.bg-primary.text-white.rounded
  .display-4
    What do you want to learn today?

  .p-4 
  - if current_user
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group 
        = f.search_field :title_or_short_description_cont, placeholder: "Find a course", class: 'form-control-sm', style: 'float: left;'
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}        

  -# .container.my-2.my-lg-0
  -#   = form_tag(courses_path, method: :get) do
  -#     .input-group
  -#       = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
  -#       %span.input-group-append
  -#         %button.btn.btn-primary.btn-sm{:type => "submit"}
  -#           %span.fa.fa-search{"aria-hidden" => "true"}

.card-group 
  .card.card-body
    %h1
      .fa.fa-graduation-cap 
    = Course.count 
    online courses 
    .row
    Explore a variety of fresh topics 
  .card.card-body 
    %h1
      .fa.fa-chalkboard-teacher
    = Course.distinct.count(:user_id) 
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body 
    %h1
      .fa.fa-user-graduate
    = User.count 
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body 
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule
%hr

%h2
  .fa.fa-user-graduate
  Continue Learning
.col-lg-10.order-1.order-lg-1
  .row.row-cols-1.row-cols-md-3.g-4
    - @purchased_courses.each do |course|
      = render 'courses/course', course: course

%hr
%h2
  .fa.fa-chart-line 
  Popular Courses
.col-lg-10.order-1.order-lg-1
  .row.row-cols-1.row-cols-md-3.g-4
    - @popular_courses.each do |course|
      = render 'courses/course', course: course

%hr
%h2
  .fa.fa-star
  Top Rated Courses
.col-lg-10.order-1.order-lg-1
  .row.row-cols-1.row-cols-md-3.g-4
    - @top_rated_courses.each do |course|
      = render 'courses/course', course: course

%hr
%h2
  .fa.fa-clock
  Latest Courses
.col-lg-10.order-1.order-lg-1
  .row.row-cols-1.row-cols-md-3.g-4
    - @latest_courses.each do |course|
      = render 'courses/course', course: course

%hr
%h2
  .fa.fa-comment
  What our students are saying
.col-lg-10.order-1.order-lg-1
  .row.row-cols-1.row-cols-md-3.g-4
    - @latest_good_reviews.each do |enrollment|
      = render 'enrollments/enrollment', enrollment: enrollment


%hr