config/routes.rb
Rails.application.routes.draw do
  
  resources :enrollments do
    get :my_students, on: :collection
  end
  devise_for :users
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
  namespace :charts do
    get 'money_makers'
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
  end
  root "home#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  #Course.find_each { |course| Course.reset_counters(course.id, :enrollments)} # this updates the counter cache number of enrollments
  belongs_to :user, counter_cache: true
  #User.find_each { |user| User.reset_counters(user.id, :enrollments)}

  validates :user, :course, presence: true

  validates_presence_of :rating, if: :review? #you have to leave both a rating and a review
  validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :course_id #so user can't subscribe twice
  validates_uniqueness_of :course_id, scope: :user_id

  scope :pending_review, -> {where(rating: [0, nil, ""], review: [0, nil, ""])}
  scope :reviewed, -> {where.not(review: [0, nil, ""])}
  scope :latest_good_reviews, -> { order(rating: :desc, created_at: :desc).limit(3)}

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  def self.ransackable_attributes(auth_object = nil)
    %w[review rating price] + _ransackers.keys # add any other attributes you want to allowlist for searching
  end
  def self.ransackable_associations(auth_object = nil)
    %w[user course]
  end

  def to_s
    user.to_s + " " + course.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  after_destroy do
    course.update_rating
  end


  validate :cant_subscribe_to_own_course
  protected
  def cant_subscribe_to_own_course
    if self.new_record?
      if user_id == course.user_id
        errors.add(:base, "you can't subscribe to your own course")
      end
    end
  end



end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :set_course, only: [:new, :create]
  # GET /enrollments or /enrollments.json
  def index
    #@enrollments = Enrollment.all
    #@pagy, @enrollments = pagy(Enrollment.all)
    @ransack_path = enrollments_path
    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    authorize @enrollments
  end

  #this pulls all enrollments for all classes created by a teacher
  def my_students
    @ransack_path = my_students_enrollments_path
    @q = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index' 
  end

  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  def edit
    authorize @enrollment
  end

  def create
    if @course.price > 0
      flash[:alert] = "you cannot access paid courses yet"
      redirect_to new_course_enrollment_path(@course)
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "you are enrolled"
    end

  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:course_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit( :rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.haml
.col
  .card.h-100
    .card-header 
      .fa.fa-user 
      = link_to enrollment.user.username, user_path(enrollment.user)
      .fa.fa-clock 
      = time_ago_in_words(enrollment.updated_at)
      .fa.fa-graduation-cap 
      = link_to enrollment.course, course_path(enrollment.course)
    .card-body 
      .text-warning.fa.fa-star
      %b= enrollment.rating
      .fa.fa-comment
      %small= enrollment.review 
    - if current_user
      .card-footer 
        - if policy(enrollment).edit?
          = link_to 'Edit Review', edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :rating, collection: 1..5 #, as: :radio_buttons
    = f.input :review


  .form-actions
    = f.button :submit

app/views/enrollments/edit.html.haml
- content_for :title do
  what 
  \|
  Enroll 
  = @enrollment

.card 
  .card-header 
    %h3 
      .text-warning.fa.fa-star
      Add a Review
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show Review', @enrollment
    \|
    = link_to 'Back to course', course_path(@enrollment.course)

app/views/enrollments/index.html.haml
- content_for :title do
  what
  \|
  All Enrollments

%h3
  .text-center 
    = action_name.humanize
    enrollments 
    .badge.bg-info 
      = @enrollments.count

.form-inline 
  = search_form_for @q, url: @ransack_path do |f|
    = f.search_field :review_cont, placeholder: 'review'
    = f.search_field :user_email_cont, placeholder: 'email'
    = f.search_field :course_title_cont, placeholder: 'course'
    = f.search_field :rating_eq, placeholder: 'rating'
    = f.search_field :price_eq, placeholder: 'price'
    = f.submit 
    = link_to 'refresh', @ransack_path

.table-responsive
  %table.table.table-bordered.table-striped.table-sm
    %thead
      %tr
        %th ID
        %th= sort_link(@q, :user_email, "User")

        %th
          .fa.fa-clock 
          = sort_link(@q, :created_at)
        %th 
          
          .fa.fa-graduation-cap
          = sort_link(@q, :course_title, "Course")
        %th 
          
          .fa.fa-dollar-sign
          = sort_link(@q, :price)
        %th 
          .text-warning.fa.fa-clock
          = sort_link(@q, :updated_at)
        %th 
          .text-warning.fa.fa-star
          = sort_link(@q, :rating)
        %th 
          .text-warning.fa.fa-comment
          Review
        %th Progress
        %th
        %th
        %th

    %tbody
      - @enrollments.each do |enrollment|
        %tr
          %td= enrollment.id
          %td= link_to enrollment.user, user_path(enrollment.user)
          %td= enrollment.created_at.strftime("%d/%b %Y %H:%M")
          %td= link_to enrollment.course, course_path(enrollment.course)
          %td= number_to_currency(enrollment.price) 
          %td
            - if enrollment.rating.present?
              = enrollment.updated_at.strftime("%d/%b %Y %H:%M")
          %td= enrollment.rating
          %td= enrollment.review
          %td= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0)
          %td= link_to 'See Review', enrollment
          %td
            - if policy(enrollment).edit?
              = link_to 'Add Review', edit_enrollment_path(enrollment)
          %td
            - if policy(enrollment).destroy?
              = link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }
!= pagy_bootstrap_nav(@pagy)
%br

app/views/enrollments/new.html.haml
- content_for :title do
  what 
  \|
  Enroll 
  = @enrollment

.card 
  .card-header 
    %h3 
      .fa.fa-graduation-cap
      = link_to @course.title, course_path(@course)
      %hr
      .fa.fa-lock-open 
      Buy Course 
  .card-body
    = form_tag course_enrollments_path(@course) do
      = submit_tag "Pay #{@course.price}", class: 'btn btn-lg btn-success'
  .card-footer
    = link_to 'Back', course_path(@course)

app/views/enrollments/show.html.haml
= render 'enrollments/enrollment', enrollment: @enrollment