config/routes.rb
Rails.application.routes.draw do
  
  resources :enrollments do
    get :my_students, on: :collection
  end
  devise_for :users
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
  namespace :charts do
    get 'money_makers'
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
  end
  root "home#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%hr
%footer
  .containter 
    .row 
      .col-md-4 
        Copyright 
        @
        = Time.now.year 
        CoursePlatform Sp. z o.o 
        .row 
        .fa.fa-envelope 
        = mail_to 's@s.com'
        .row 
      .col-md-4 
        Privacy Policy 
        .row 
        Terms and Conditions 
      .col-md-4 
        About Us 
        .row 
        = link_to 'Teach on ddddd', new_course_path 
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "/"} Rubygems
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user

      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link d-flex align-items-center' do
            .fa.fa-home{ :style => "margin-right: 10px;"}
            Home
        
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link d-flex align-items-center' do
            .fa.fa-graduation-cap{ :style => "margin-right: 10px;"}
            Courses
        /SEARCH IN NAVBAR
        .form-inline
          = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
            .input-group 
              = f.search_field :title_or_short_description_cont, placeholder: "Find a course", class: 'form-control-sm', style: 'float: left;'
              %span.input-group-append
                %button.btn.btn-primary.btn-sm{:type => "submit"}
                  %span.fa.fa-search{"aria-hidden" => "true"} 

        -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
        -#   = link_to new_course_path, class: 'nav-link d-flex align-items-center' do
        -#     .fa.fa-plus.align-items-center{ :style => "margin-right: 10px;"}
        -#     %p(style="width: 100px; margin-bottom: 0;")="New Course"
             
        -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
        -#   = link_to users_path, class: 'nav-link d-flex align-items-center' do
        -#     .fa.fa-users.align-items-center{ :style => "margin-right: 10px;"}
        -#     %p(style=" margin-bottom: 0;")="Users"
        -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(enrollments_path)}"}
        -#   = link_to enrollments_path, class: 'nav-link d-flex align-items-center' do
        -#     .fa.fa-lock-open.align-items-center{ :style => "margin-right: 10px;"}
        -#     %p(style=" margin-bottom: 0;")="Enrollments"
        %ul.navbar-nav.mr-auto  
        - if current_user.has_role?(:student)
          %li.nav-item.dropdown.flex-fill(style="display: inline-block;")
            %a#studentDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-graduation-cap
              Learn
              
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "studentDropdown"}
              = link_to purchased_courses_path, class: "dropdown-item" do
                .fa.fa-graduation-cap
                %b Purchased Courses
                .badge.bg-danger
                  = current_user.enrollments_count
              = link_to pending_review_courses_path, class: "dropdown-item" do
                .fa.fa-star
                %b Pending Review
                .badge.bg-danger
                  = current_user.enrollments.pending_review.count
        - if current_user.has_role?(:teacher)
          %li.nav-item.dropdown.flex-fill(style="display: inline-block;")
            %a#teacherDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-chalkboard-teacher
              Teach
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "teacherDropdown"}
              = link_to new_course_path, class: "dropdown-item" do
                .fa.fa-plus
                %b New Course
              = link_to created_courses_path, class: "dropdown-item" do
                .fa.fa-graduation-cap
                %b My Courses
                .badge.bg-danger
                  = current_user.courses_count
              = link_to my_students_enrollments_path, class: "dropdown-item" do
                .fa.fa-users
                %b My Students
                .badge.bg-danger
                  = Enrollment.joins(:course).where(courses: {user: current_user}).count

        - if current_user.has_role?(:admin)
          %li.nav-item.dropdown.flex-fill(style="display: inline-block;")
            %a#adminDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-cogs
              Admin
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "adminDropdown"}
              = link_to users_path, class: "dropdown-item" do
                .fa.fa-users
                %b Users
                .badge.bg-danger
                  = User.count
              = link_to enrollments_path, class: "dropdown-item" do
                .fa.fa-lock-open
                %b Enrollments
                .badge.bg-danger
                  = Enrollment.count
              = link_to activity_path, class: "dropdown-item" do
                .fa.fa-bell
                %b Activity 
              = link_to analytics_path, class: "dropdown-item" do
                .fa.fa-chart-line
                %b Analytics

     
      -# .container
      -#   = form_tag(courses_path, method: :get) do
      -#     .input-group
      -#       = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
      -#       %span.input-group-append
      -#         %button.btn.btn-primary.btn-sm{:type => "submit"}
      -#           %span.fa.fa-search{"aria-hidden" => "true"}
      
        -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(activity_path)}"}
        -#   = link_to activity_path, class: 'nav-link d-flex align-items-center' do
        -#     .fa.fa-bell.align-items-center{ :style => "margin-right: 10px;"}
        -#     Activity
      %ul.navbar-nav.mr-right(style="display: flex;")
        %li.nav-item.dropdown.flex-fill(style="display: inline-block;")
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
            %b= current_user.username
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      .d-flex.justify-content-between.align-items-center
        = content_tag :div, msg, :id => "flash_#{name}"
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", type: "button"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    /%title Rubygems
    %title
      = content_for?(:title) ? yield(:title) : "what"
        
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://www.gstatic.com/charts/loader.js'
    = javascript_include_tag 'chartkick'

    %script{:async => "", :crossorigin => "anonymous", :integrity => "sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D", :src => "https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"}
    %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
      %br
    .bg-secondary
      = render 'layouts/footer'